spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:51608/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=GuKjjaHMQEGqmTBwRoInEuvBkKslOWoy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}